const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');


module.exports = {
    mode: "development", // "production" | "development" | "none"  // Chosen mode tells webpack to use its built-in optimizations accordingly.
    entry: "./src", // string | object | array  // defaults to './src'
    // Here the application starts executing
    // and webpack starts bundling
    devServer: {
        contentBase: path.join(__dirname, 'dist'),
    },
    output: {
        // options related to how webpack emits results
        path: path.resolve(__dirname, "dist"), // string
        // the target directory for all output files
        // must be an absolute path (use the Node.js path module)
        filename: "bundle.js", // string    // the filename template for entry chunks
        publicPath: "/assets/", // string    // the url to the output directory resolved relative to the HTML page
        library: "MyLibrary", // string,
        // the name of the exported library
        libraryTarget: "umd", // universal module definition    // the type of the exported library
        /* Advanced output configuration (click to show) */
    },
    module: {
        // configuration regarding modules
        rules: [
            // rules for modules (configure loaders, parser options, etc.)
            {
                test: /\.jsx?$/,
                include: [
                    path.resolve(__dirname, "src")
                ],
                loader: "babel-loader",
            },
            {
              test: /\.(eot|otf|ttf|woff|woff2)$/,
              use: [
                {
                  loader: 'file-loader',
                  options: {
                    outputPath: 'fonts/'
                  }
                }
              ]
            },
            {
              test: /\.html$/,
              use: 'html-loader',
            },
        ]
    },
    plugins: [
      new HtmlWebpackPlugin({
        inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
        template: 'src/index.html',
      }),
    ]
}